Repository PrinceBharti27/Open_Source, pull requests merged in 2022-10, with the labels that each got.

#1 Added Test-Hashing Project
  Text-Hashing/.gitignore
  Text-Hashing/README.md
  Text-Hashing/package-lock.json
  Text-Hashing/package.json
  Text-Hashing/public/favicon-16x16.png
  Text-Hashing/public/favicon-32x32.png
  Text-Hashing/public/favicon.ico
  Text-Hashing/public/index.html
  Text-Hashing/public/manifest.json
  Text-Hashing/public/robots.txt
  Text-Hashing/src/App.css
  Text-Hashing/src/App.js
  Text-Hashing/src/App.test.js
  Text-Hashing/src/components/About.js
  Text-Hashing/src/components/Alert.js
  Text-Hashing/src/components/Navbar.js
  Text-Hashing/src/components/Textforms.js
  Text-Hashing/src/index.css
  Text-Hashing/src/index.js
  Text-Hashing/src/logo.svg
  Text-Hashing/src/reportWebVitals.js
  Text-Hashing/src/setupTests.js
Labels: hactoberfest-accepted

#2 Added LICENSE
  LICENSE
Labels: enhancement, help wanted

#5 Added Clock
  Clock/Clock-master/.all-contributorsrc
  Clock/Clock-master/.gitignore
  Clock/Clock-master/README.md
  Clock/Clock-master/images/clock-dark.png
  Clock/Clock-master/images/clock.png
  Clock/Clock-master/index.html
  Clock/Clock-master/screenshots/ss1.png
  Clock/Clock-master/screenshots/ss2.png
  Clock/Clock-master/screenshots/ss3.png
  Clock/Clock-master/script.min.js
  Clock/Clock-master/styles.min.css
Labels: hactoberfest-accepted

#4 Added ReadMe
  README.md
Labels: enhancement, hactoberfest-accepted

#6 auth in python
  authproject/app/__init__.py
  authproject/app/__pycache__/__init__.cpython-39.pyc
  authproject/app/__pycache__/admin.cpython-39.pyc
  authproject/app/__pycache__/apps.cpython-39.pyc
  authproject/app/__pycache__/models.cpython-39.pyc
  authproject/app/__pycache__/urls.cpython-39.pyc
  authproject/app/__pycache__/views.cpython-39.pyc
  authproject/app/admin.py
  authproject/app/apps.py
  authproject/app/migrations/__init__.py
  authproject/app/migrations/__pycache__/__init__.cpython-39.pyc
  authproject/app/models.py
  authproject/app/templates/app.html
  authproject/app/tests.py
  authproject/app/urls.py
  authproject/app/views.py
  authproject/authproject/__init__.py
  authproject/authproject/__pycache__/__init__.cpython-39.pyc
  authproject/authproject/__pycache__/settings.cpython-39.pyc
  authproject/authproject/__pycache__/urls.cpython-39.pyc
  authproject/authproject/__pycache__/wsgi.cpython-39.pyc
  authproject/authproject/asgi.py
  authproject/authproject/settings.py
  authproject/authproject/urls.py
  authproject/authproject/wsgi.py
  authproject/db.sqlite3
  authproject/manage.py
Labels: hactoberfest-accepted
